relative_links:
    enabled: true
    collections: true

name: Literatur Epochen von Realismus bis Postmoderne

title: null

include:
    - index.md
    - Moderne.md
    - Exilliteratur.md
    - Naturalismus.md
    - Neue Sachlichkeit.md
    - Trümmerliteratur.md
    - Postmoderne.md
    - Biedermeier.md
    - Expressionismus.md
    - Realismus.md
    - Vormärz.md
